CREATE TABLE LEASE
(
    LEASE_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    LEASE_START_DT  TIMESTAMP     NOT NULL,
    LEASE_END_DT  TIMESTAMP     NOT NULL,
    LEASE_STATUS     VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)     NOT NULL,
    CREATED_TS      TIMESTAMP        NOT NULL,
    UPDATED_BY      VARCHAR(100)     NOT NULL,
    UPDATED_TS      TIMESTAMP        NOT NULL

)