CREATE TABLE UNIT
(
    UNIT_ID   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    PROP_ID     BIGINT           NOT NULL,
    UNIT_NUMBER     VARCHAR(100)     NOT NULL,
    UNIT_TYPE       VARCHAR(100)     NOT NULL,
    UNIT_STATUS     VARCHAR(100)     NOT NULL,
    UNIT_PRICE      DECIMAL(10,2)    NOT NULL,
    UNIT_AREA       DECIMAL(10,2)    NOT NULL,
    UNIT_BEDROOM    INT              NOT NULL,
    UNIT_BATHROOM   INT              NOT NULL,
    UNIT_FLOOR      INT              NOT NULL,
    UNIT_GARAGE     INT              NOT NULL,
    UNIT_DESCRIPTION VARCHAR(1000)    NOT NULL,
    UNIT_IMAGE      VARCHAR(1000)    NOT NULL,
    CREATED_BY      VARCHAR(100)     NOT NULL,
    CREATED_TS      TIMESTAMP        NOT NULL,
    UPDATED_BY      VARCHAR(100)     NOT NULL,
    UPDATED_TS      TIMESTAMP        NOT NULL,
    CONSTRAINT FK_PROP_ID  FOREIGN KEY (PROP_ID) REFERENCES PROPERTY(PROP_ID)
)