CREATE TABLE PROPERTY
(
    PROP_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    PROP_ADRES_L1  VARCHAR(500)     NOT NULL,
    PROP_ADRES_L2  VARCHAR(100)     NOT NULL,
    PROP_ADRES_L3  VARCHAR(200)     NULL,
    PROP_CITY       VARCHAR(20)     NOT NULL,
    PROP_STATE      VARCHAR(20)     NOT NULL,
    PROP_COUNTRY    VARCHAR(20)     NOT NULL,
    PROP_ZIP        VARCHAR(20)     NOT NULL,
    PROP_STATUS     VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)     NOT NULL,
    CREATED_TS      TIMESTAMP        NOT NULL,
    UPDATED_BY      VARCHAR(100)     NOT NULL,
    UPDATED_TS      TIMESTAMP        NOT NULL

)