CREATE TABLE TENANT
(
    TENANT_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    TENANT_NAME  VARCHAR(100)     NOT NULL,
    TENANT_DOB   VARCHAR(20)     NOT NULL,
    TENANT_GOV_ID  VARCHAR(20)   NULL,
    LEASE_ID        BIGINT      NOT NULL,
    IS_PRIMARY      BOOLEAN     NOT NULL,
    CREATED_BY      VARCHAR(100)     NOT NULL,
    CREATED_TS      TIMESTAMP        NOT NULL,
    UPDATED_BY      VARCHAR(100)     NOT NULL,
    UPDATED_TS      TIMESTAMP        NOT NULL
)