CREATE TABLE WORK_ORDER
(
    WORK_ORDER_ID   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    PROPERTY_ID     BIGINT          NOT NULL,
    UNIT_ID         BIGINT          NOT NULL,
    LEASE_ID        BIGINT          NOT NULL,
    WO_REPORT_DATE  TIMESTAMP       NOT NULL,
    WO_START_DATE   TIMESTAMP       NOT NULL,
    WO_END_DATE     TIMESTAMP       NOT NULL,
    WO_COST         VARCHAR(100)     NOT NULL,
    CREATED_BY      VARCHAR(100)     NOT NULL,
    CREATED_TS      TIMESTAMP        NOT NULL,
    UPDATED_BY      VARCHAR(100)     NOT NULL,
    UPDATED_TS      TIMESTAMP        NOT NULL
)